config/routes.rb
Rails.application.routes.draw do

  root "dashboards#home"

  get 'dashboards/home'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :questions
  resources :keywords
  resources :notes
  resources :topics

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :notes
  has_many :keywords
  has_many :questions

  belongs_to :user
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_filter :authorize

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @notes = Note.where(topic_id: params[:id])
    @questions = Question.where(topic_id: params[:id])
    @keywords = Keyword.where(topic_id: params[:id])
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:subject)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/_note.html.erb
<tr>
  <td><%= note.note %></td>
  <td><%= link_to 'Show', note %></td>
  <td><%= link_to 'Edit', edit_note_path(note) %></td>
  <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Topics</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <p><tr>
        <td><%= topic.subject %></td>
        <td><%= link_to 'Show', notes_path %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr></p>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<h1><p class="topicSubject"><%= @topic.subject %></p></h1>
<br />

<table>
  <thead>
    <tr>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="notes_tbody">
    <%= render @notes %>
  </tbody>
</table>
<br />
<br />
<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="question_tbody">
    <%= render @questions %>
  </tbody>
</table>
<br />
<br />

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th>Definition</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="keyword_tbody">
     <%= render @keywords %>
  </tbody>
</table>
<br />
<br />
<div>
<%= link_to 'New Keyword', new_keyword_path, remote: true %> |
<%= link_to 'New Note', new_note_path, remote: true %> |
<%= link_to 'New Question', new_question_path, remote: true %>
</div>

<div id="new_keyword_form"></div>
<div id="new_note_form"></div>
<div class="new_question_form"></div>
<br />
<br />




<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>