config/routes.rb
Rails.application.routes.draw do

  root "dashboards#home"

  get 'dashboards/home'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :questions
  resources :keywords
  resources :notes
  resources :topics

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  belongs_to :topic
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :set_keyword, only: [:show, :edit, :update, :destroy]
  before_filter :authorize

  # GET /keywords
  # GET /keywords.json
  def index
    @keywords = Keyword.all
  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
  end

  # GET /keywords/new
  def new
    @keyword = Keyword.new
  end

  # GET /keywords/1/edit
  def edit
  end

  # POST /keywords
  # POST /keywords.json
  def create
    @keyword = Keyword.new(keyword_params)
    @keyword.save
  end

  # PATCH/PUT /keywords/1
  # PATCH/PUT /keywords/1.json
  def update
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { render :show, status: :ok, location: @keyword }
      else
        format.html { render :edit }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword.destroy
    respond_to do |format|
      format.html { redirect_to keywords_url, notice: 'Keyword was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def keyword_params
      params.require(:keyword).permit(:word, :definition, :topic_id)
    end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.erb
<%= form_for(@keyword, remote: true) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% @keyword.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :definition %><br>
    <%= f.text_area :definition %>
  </div>
  <div class="field">
    <%= f.label :topic_id %>
    <%= f.collection_select(:topic_id, Topic.order(:subject), :id, :subject, {:prompt => 'Select'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keywords/_keyword.html.erb
<tr>
  <td><%= keyword.word %></td>
  <td><%= keyword.definition %></td>
  <p class= "show_edit_destroy">
    <td><%= link_to 'Show', keyword %></td>
    <td><%= link_to 'Edit', edit_keyword_path(keyword) %></td>
    <td><%= link_to 'Destroy', keyword, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </p>
</tr>

app/views/keywords/create.js.erb
$("#keyword_tbody").append("<%= j(render @keyword)%>")
$(".new_keyword").hide()

app/views/keywords/edit.html.erb
<h1>Editing Keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Keywords</h1>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th>Definition</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="keyword_tbody">
     <%= render @keywords %>
  </tbody>
</table>

<br>

<%= link_to 'New Keyword', new_keyword_path, remote: true %>

<div id="new_keyword_form"></div>

app/views/keywords/new.js.erb
$("#new_keyword_form").html("<%= j(render 'form') %>");

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @keyword.word %>
</p>

<p>
  <strong>Definition:</strong>
  <%= @keyword.definition %>
</p>

<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>